### ISSUE TITLE
Implement "Copy tarball and symlink" task to playbook

### ISSUE THREAD

**Issue by rhiniodontypus** [rhiniodontypus/userdata-playbook#5]
- Implement task to playbook: Copy tarball and symlink
```
- hosts: dnbdserver
  name: Copy tarball and sym link
  become: true
  tasks: 
    copy: tarball -> image.netboot...
```
